# Generated by Django 4.1.7 on 2023-03-11 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='investors', verbose_name='Фото')),
                ('about', models.TextField(verbose_name='Обо мне')),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Инвестор',
                'verbose_name_plural': 'Инвесторы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, help_text='Фотографии для загрузки', null=True, upload_to='business_owners', verbose_name='Фото')),
                ('sphere', models.CharField(help_text='Сфера деятельности', max_length=100, null=True, verbose_name='Сфера')),
                ('business_name', models.CharField(max_length=100, null=True, verbose_name='Название бизнеса')),
                ('contact_info', models.TextField(help_text='Для связи', null=True, verbose_name='Контактная информация')),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Владелец бизнеса',
                'verbose_name_plural': 'Владельцы бизнесов',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заблокированный пользователь',
                'verbose_name_plural': 'Заблокированные пользователи',
                'ordering': ['-id'],
            },
        ),
    ]
